### ISSUE TITLE
Evicted builds can be retried

### ISSUE THREAD

**Issue by smarterclayton** [openshift/ci-operator#274]
If a build fails with:

```
status:
  message: 'Pod The node was low on resource: [DiskPressure]. '
  phase: Failed
  reason: Evicted
  startTime: 2019-02-19T02:02:50Z
```

the build can be restarted by the next caller. It does not currently.
