### ISSUE TITLE
[rfe] targets dependency management

### ISSUE THREAD

**Issue by mjudeikis** [openshift/ci-operator#276]
Ou test jobs are depending on multiple targets to be completed. In example:
```
    name: pull-ci-openshift-openshift-azure-master-e2e-upgrade-v1.2
    rerun_command: /test e2e-upgrade-v1.2
    spec:
      containers:
      - args:
        - --artifact-dir=$(ARTIFACTS)
        - --give-pr-author-access-to-namespace=true
        - --target=[images]
        - --target=[output:stable:azure-controllers]
        - --target=[output:stable:etcdbackup]
        - --target=[output:stable:metricsbridge]
        - --target=[output:stable:sync]
        - --target=rbac
        - --target=e2e-upgrade-v1.2
```

Upgrade job `e2e-upgrade-v1.2` job is building OSA cluster and testing upgrade process from stable code to testing code.
In this example, cluster creation requires images to be available and images have to be available to be pulled from outside (hence rbac template to create a policy to open images for temporary namespace) 
```
        - --target=[output:stable:azure-controllers]
        - --target=[output:stable:etcdbackup]
        - --target=[output:stable:metricsbridge]
        - --target=[output:stable:sync]
        - --target=rbac
```

In this case, we need to be able to specify that the target `e2e-upgrade-v1.2` has a hard dependency on multiple targets to be completed before.

Related: https://github.com/openshift/ci-operator-prowgen/issues/79 

/cc @petr-muller @stevekuznetsov @droslean
